// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkXDCIYpUfAEsur1RpGDGpyseriL0j0Q',
    appId: '1:139034063593:android:725de3df2782ef13627678',
    messagingSenderId: '139034063593',
    projectId: 'clickbuy-e9657',
    storageBucket: 'clickbuy-e9657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnabfvS8Tc2aqpmBTb1z6aLRUW9FjsLE',
    appId: '1:139034063593:ios:b0d032abd94cb97e627678',
    messagingSenderId: '139034063593',
    projectId: 'clickbuy-e9657',
    storageBucket: 'clickbuy-e9657.firebasestorage.app',
    androidClientId: '139034063593-svvgqaea25qs4qcruddncem04rvl3joo.apps.googleusercontent.com',
    iosClientId: '139034063593-0vp4gq3acdr6pfvl3148cptpdammrpnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnabfvS8Tc2aqpmBTb1z6aLRUW9FjsLE',
    appId: '1:139034063593:ios:b0d032abd94cb97e627678',
    messagingSenderId: '139034063593',
    projectId: 'clickbuy-e9657',
    storageBucket: 'clickbuy-e9657.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1jLsSLIGkF0_wvxVNJVp_4z84qYh34y4',
    appId: '1:139034063593:web:48daa133c6b23d59627678',
    messagingSenderId: '139034063593',
    projectId: 'clickbuy-e9657',
    authDomain: 'clickbuy-e9657.firebaseapp.com',
    storageBucket: 'clickbuy-e9657.firebasestorage.app',
    measurementId: 'G-ZJRFL32JSB',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1jLsSLIGkF0_wvxVNJVp_4z84qYh34y4',
    appId: '1:139034063593:web:48daa133c6b23d59627678',
    messagingSenderId: '139034063593',
    projectId: 'clickbuy-e9657',
    authDomain: 'clickbuy-e9657.firebaseapp.com',
    storageBucket: 'clickbuy-e9657.firebasestorage.app',
    measurementId: 'G-ZJRFL32JSB',
  );

}